### ISSUE TITLE
zk, kafka, kafka-stack: podAffinityTerm.topologyKey: Required value: can not be empty

### ISSUE THREAD

**Issue by Analect** [Mirantis/k8s-apps#10]
Was trying to get the kafka-stack running against a version 1.72 kub cluster on GKE and helm 2.5.1.  I can see from the readme that only up to kub 1.6 is supported, but wanted to flag this as something potentially needing fixing, as per the [check_helm_or_k8s_version.rst doc](https://github.com/Mirantis/k8s-apps/blob/master/docs/check_helm_or_k8s_version.rst) in here.

Trying to run this command ... 
`helm install -n kafka-stack kafka-stack/`
Error: release kafka-stack failed: StatefulSet.apps "kafka-kafka-stack" is invalid: spec.template.annotations.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Required value: can not be empty

.... or the equivalent for dependent charts ... 
`helm install -n kafka mirantisworkloads/kafka`
Error: release kafka failed: StatefulSet.apps "kafka-kafka" is invalid: spec.template.annotations.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Required value: can not be empty

... brings back the same empty topologyKey error.

`helm install -n zookeeper mirantisworkloads/zookeeper`
Error: release zookeeper failed: StatefulSet.apps "zk-zookeeper" is invalid: spec.template.annotations.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Required value: can not be empty

It seems from this [issue](https://github.com/kubernetes/kubernetes/issues/49492#issuecomment-318675700) that topologyKey can no longer be ommitted from kub version 1.7 onwards.

I can see that you include topologyKeys for the kafka and zookeeper statefulsets ... however, as per the issue linked to above and these [docs](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/), I think that `topologyKey` setting needs to reside under a `podAffinityTerm` heading.

**Comment by Kshatrix** [comment]
Thank you for reporting this, we'll try to make all charts compatible with 1.7 Kubernetes ASAP.

**Comment by Kshatrix** [comment]
Charts should work both with 1.6 and 1.7 k8s now.
