### ISSUE TITLE
Unable to start HDFS NameNode pod

### ISSUE THREAD

**Issue by rdefauw** [Mirantis/k8s-apps#7]
It crashes repeatedly, with this error in the log:

java.net.UnknownHostException: hdfs-namenode-ts-rdapp-hdfs-0: hdfs-namenode-ts-rdapp-hdfs-0: Name or service not known

**Comment by Kshatrix** [comment]
Fixed by If26ecd926298c3147d722435ccbd4d6517ee0b4e
